CC = g++
C_STANDARD = -std=c11
OBJECT_FLAG = -c
TARGET = raising_module_numbers

raising_module_numbers: raising_module_numbers.cpp raising_module_numbers.h
    $(CC) -o raising_module_numbers raising_module_numbers.cpp

clean:
    rm -rf *.o raising_module_numbers
